### ISSUE TITLE
Move to organisation

### ISSUE THREAD

**Issue by bwesterb** [open-mpic/draft-mpic#1]
Shall we move this repo to an organisation?

**Comment by sciros** [comment]
I would say we probably should, but I don't have any recommendations myself apart from a community-oriented org like open-mpic or something major like pkic.

**Comment by birgelee** [comment]
I would be happy to host this at the open-mpic org. We could give everyone accounts in the org. I am also fine moving to a different organization if it is preferable.

**Comment by bwesterb** [comment]
I'm happy with moving this to open-mpic.

**Comment by birgelee** [comment]
To this end, I invited everyone on this repo as a member of open-mpic. My understanding is this should allow you to create repos. @bwesterb I believe you can go into settings and change ownership to move this into the open-mpic org after you accept the invitation.

**Comment by bwesterb** [comment]
Move is done, thanks!
