### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by bwesterb** [open-mpic/draft-mpic#14]
@birgelee could you set "Workflow permissions" to "Read and write permissions" [in the repository settings](https://github.com/open-mpic/draft-mpic/settings/actions#actions_default_workflow_permissions_write)? That probably fixed the build. I lost admin rights after transferring #1

**Comment by birgelee** [comment]
I had to change this at the org level, but it should be updated now. Please let me know if you the run is still having issues.

**Comment by bwesterb** [comment]
That fixed it. Thanks.
